"""Interactive Streamlit demo for the BANKING77 classifier.

Course-lab mapping: post-lab application for Lab 07 (final evaluation).
Reference basis: results and figures generated by the final evaluation lab.
The dashboard consumes saved artifacts and does not retrain or alter the test split.
"""

from pathlib import Path
import json


BANKING77_INTENTS = [
    "activate_my_card", "age_limit", "apple_pay_or_google_pay", "atm_support",
    "automatic_top_up", "balance_not_updated_after_bank_transfer",
    "balance_not_updated_after_cheque_or_cash_deposit", "beneficiary_not_allowed",
    "cancel_transfer", "card_about_to_expire", "card_acceptance", "card_arrival",
    "card_delivery_estimate", "card_linking", "card_not_working",
    "card_payment_fee_charged", "card_payment_not_recognised",
    "card_payment_wrong_exchange_rate", "card_swallowed", "cash_withdrawal_charge",
    "cash_withdrawal_not_recognised", "change_pin", "compromised_card",
    "contactless_not_working", "country_support", "declined_card_payment",
    "declined_cash_withdrawal", "declined_transfer",
    "direct_debit_payment_not_recognised", "disposable_card_limits",
    "edit_personal_details", "exchange_charge", "exchange_rate", "exchange_via_app",
    "extra_charge_on_statement", "failed_transfer", "fiat_currency_support",
    "get_disposable_virtual_card", "get_physical_card", "getting_spare_card",
    "getting_virtual_card", "lost_or_stolen_card", "lost_or_stolen_phone",
    "order_physical_card", "passcode_forgotten", "pending_card_payment",
    "pending_cash_withdrawal", "pending_top_up", "pending_transfer", "pin_blocked",
    "receiving_money", "Refund_not_showing_up", "request_refund",
    "reverted_card_payment?", "supported_cards_and_currencies", "terminate_account",
    "top_up_by_bank_transfer_charge", "top_up_by_card_charge",
    "top_up_by_cash_or_cheque", "top_up_failed", "top_up_limits", "top_up_reverted",
    "topping_up_by_card", "transaction_charged_twice", "transfer_fee_charged",
    "transfer_into_account", "transfer_not_received_by_recipient", "transfer_timing",
    "unable_to_verify_identity", "verify_my_identity", "verify_source_of_funds",
    "verify_top_up", "virtual_card_not_working", "visa_or_mastercard",
    "why_verify_identity", "wrong_amount_of_cash_received",
    "wrong_exchange_rate_for_cash_withdrawal",
]



def intent_category(intent: str) -> str:
    """Map a BANKING77 intent to a readable banking domain."""
    name = intent.lower()
    if any(word in name for word in ("card", "visa", "mastercard", "contactless", "pin")):
        return "Cards and payments"
    if any(word in name for word in ("cash", "withdrawal", "atm")):
        return "Cash and ATMs"
    if any(word in name for word in ("transfer", "beneficiary", "receiving_money", "recipient")):
        return "Transfers"
    if any(word in name for word in ("top_up", "topping_up")):
        return "Top-ups"
    if any(word in name for word in ("verify", "identity", "source_of_funds")):
        return "Identity and verification"
    if any(word in name for word in ("exchange", "currency", "fiat")):
        return "Currencies and exchange"
    if any(word in name for word in ("account", "personal", "passcode", "phone")):
        return "Account and profile"
    return "Other banking services"



def main() -> None:
    """Render the interactive classifier dashboard."""
    import pandas as pd
    import streamlit as st
    import torch
    from transformers import AutoModelForSequenceClassification, AutoTokenizer

    # Find the saved files from the project root, no matter where Streamlit was started.
    # This page only uses the trained BANKING77 model; it does not retrain it.
    root = Path(__file__).resolve().parents[1]
    checkpoint = root / "results/05_distilbert_finetuning_checkpoint"
    metrics_path = root / "results/metrics.csv"
    comparison_figure = root / "figures/final_model_comparison_annotated.png"

    st.set_page_config(page_title="SIRIUS Bank Intelligence", page_icon="🏦", layout="wide")
    st.markdown("""
    <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');
    :root { color-scheme: light dark; --ink:#102a56; --navy:#153e73; --teal:#087f83; --canvas:#eef5fb; --surface:#ffffff; --panel:#1f5a8a; --panel-deep:#153e73; --muted:#49647d; --accent:#1f5a8a; }
    @media (prefers-color-scheme: dark) {
        :root { --ink:#eaf3fa; --navy:#1b527a; --teal:#36b8b2; --canvas:#0d1b2a; --surface:#172b3f; --panel:#1f5a8a; --panel-deep:#102a43; --muted:#c8d9e7; --accent:#9bd5f0; }
    }
    html, body, [data-testid="stAppViewContainer"], .stApp, .main, .block-container { background: var(--canvas) !important; color: var(--ink) !important; }
    [data-testid="stHeader"], [data-testid="stToolbar"] { background: var(--canvas) !important; }
    .main .block-container { background: transparent !important; }
    h1, h2, h3, h4 { font-family: 'Space Grotesk', sans-serif !important; color: var(--ink) !important; }
    p, label, .stMarkdown, [data-testid="stMarkdownContainer"] { font-family: 'DM Sans', sans-serif; color: var(--ink) !important; }
    [data-testid="stMarkdownContainer"] p, [data-testid="stMarkdownContainer"] li, [data-testid="stMarkdownContainer"] span { color: var(--ink) !important; }
    [data-testid="stWidgetLabel"] p, [data-testid="stWidgetLabel"] label, [data-testid="stWidgetLabel"] span { color: var(--ink) !important; font-weight: 600; }
    [data-baseweb="select"] > div { background: var(--surface) !important; border-color: #7f9bb6 !important; color: var(--ink) !important; }
    [data-baseweb="select"] * { color: var(--ink) !important; }
    [data-testid="stDataFrame"], [data-testid="stTable"] { background: var(--surface) !important; border-radius: 10px; }
    [data-testid="stDataFrame"] *, [data-testid="stTable"] * { color: var(--ink) !important; }
    [data-testid="stMetric"] { background: var(--panel); border: 1px solid #8eb5d2; padding: .8rem; border-radius: 16px; box-shadow: 0 4px 14px rgba(16,42,86,.12); }
    [data-testid="stMetricLabel"], [data-testid="stMetricValue"] { color: #ffffff !important; }
    [data-baseweb="tab-list"] { background: var(--panel-deep); border-radius: 14px; padding: .35rem; }
    [data-baseweb="tab"] { color: #ffffff !important; }
    [aria-selected="true"] { color: #ffe09a !important; }
    [data-testid="stSidebar"] { background: var(--panel-deep); border-right: 1px solid #427eaa; }
    [data-testid="stSidebar"] * { color: #ffffff !important; }
    .hero { padding: 1.15rem 1.6rem; border-radius: 28px; background: radial-gradient(circle at 88% 20%, rgba(244,193,83,.3), transparent 24%), linear-gradient(120deg, #15315e, #1b5685 60%, #0a7778); color: white; box-shadow: 0 18px 45px rgba(16,42,86,.18); margin-bottom: 1.4rem; }
    .hero h1 { color: white !important; font-size: 1.9rem; margin: 0; letter-spacing: -1px; }
    .hero p { color: #dceaf7 !important; font-size: .95rem; margin: .3rem 0 0; }
    .eyebrow { color: #ffe09a; text-transform: uppercase; letter-spacing: 2px; font-size: .73rem; font-weight: 700; }
    .trust { padding: .55rem .8rem; border-radius: 18px; background: rgba(255,255,255,.14); border: 1px solid rgba(255,255,255,.3); margin-top: 1.2rem; }
    .chat-bubble { padding: 1rem 1.2rem; border-radius: 18px 18px 18px 5px; background: var(--panel); border: 1px solid #8eb5d2; color: #ffffff; box-shadow: 0 8px 24px rgba(16,42,86,.1); margin: .5rem 0 1rem; }
    .chat-bubble * { color: #ffffff !important; }
    .result-bubble { padding: 1.2rem; border-radius: 18px 18px 5px 18px; background: #237c83; border: 1px solid #83c8c5; color: #ffffff; box-shadow: 0 8px 24px rgba(16,42,86,.1); }
    .result-bubble * { color: #ffffff !important; }
    .mini-label { color: #ffe09a; font-size: .78rem; text-transform: uppercase; letter-spacing: 1px; font-weight: 700; }
    .command-card { padding: .85rem 1rem; border-radius: 12px; background: #2b6c9b; border: 1px solid #8eb5d2; color: #ffffff !important; margin: .5rem 0 1rem; font-size: .78rem; line-height: 1.45; word-break: break-word; box-shadow: 0 4px 12px rgba(16,42,86,.1); }
    .command-card code, .command-card b, .command-card strong { color: #ffffff !important; background: transparent !important; }
    .command-card code { font-family: monospace; }
    .stCaption, [data-testid="stCaptionContainer"], [data-testid="stCaptionContainer"]:hover { color: var(--muted) !important; opacity: 1 !important; }
    .stTextArea label { color: var(--ink) !important; font-weight: 700 !important; }
    .stTextArea > div, .stTextArea [data-baseweb="textarea"], .stTextArea textarea { background: var(--panel) !important; color: #ffffff !important; border: 2px solid #7f9bb6 !important; border-radius: 12px !important; }
    .stTextArea [data-baseweb="textarea"] { box-shadow: 0 6px 18px rgba(16,42,86,.08); }
    .stTextArea textarea::placeholder { color: #dceaf7 !important; opacity: 1 !important; }
    .section-kicker { color: var(--accent); font-weight: 700; letter-spacing: 1px; text-transform: uppercase; font-size: .74rem; }
    .atlas-card { padding: 1.25rem 1.4rem; border-radius: 20px; background: var(--panel); border: 1px solid #8eb5d2; color: #ffffff; margin: 1rem 0 1.2rem; box-shadow: 0 5px 18px rgba(16,42,86,.06); }
    .atlas-card * { color: #ffffff !important; }
    .atlas-card strong { color: #ffe09a !important; }
    .stButton > button { background: var(--navy) !important; color: #ffffff !important; border: 1px solid var(--navy) !important; border-radius: 12px !important; font-weight: 600 !important; box-shadow: 0 5px 14px rgba(16,42,86,.15); }
    .stButton > button:hover, .stButton > button:focus { background: var(--teal) !important; color: #ffffff !important; border-color: var(--teal) !important; }
    </style>
    """, unsafe_allow_html=True)
    st.caption("Interactive inference dashboard | Saibou KEITA")

    if metrics_path.exists():
        metrics = pd.read_csv(metrics_path)
        best = metrics.loc[metrics["macro_f1"].idxmax()]
    else:
        metrics = pd.DataFrame()
        best = {"macro_f1": 0.0, "accuracy": 0.0}

    with st.sidebar:
        st.markdown("### 🏦 SIRIUS BANK")
        st.caption("Digital banking intelligence desk")
        st.caption("Reproducibility seed: 42")
        st.info("Ask naturally. The desk maps your message to one of the 77 BANKING77 intents.")
        st.divider()
        st.markdown("**Private by design**")
        st.caption("Your query is evaluated locally by the saved checkpoint. No banking account data is required.")
        st.subheader("Run locally")
        st.markdown('<div class="command-card">▶ <b>Streamlit</b><br><code>conda run -n nlp-banking streamlit run app/app.py</code></div>', unsafe_allow_html=True)
        st.subheader("Open MLflow")
        st.markdown('<div class="command-card">◈ <b>MLflow dashboard</b><br><code>conda run -n nlp-banking mlflow ui --backend-store-uri sqlite:///$(pwd)/mlflow.db</code></div>', unsafe_allow_html=True)

    # Each tab shows one part of the project: the data, predictions, intent details,
    # model results, or the errors that still need attention.
    data_dashboard, predict, atlas, model_lab, errors = st.tabs(["Data explorer", "Predict intent", "Intent atlas", "Model lab", "Error analysis"])
    st.markdown('<div class="hero"><div class="eyebrow">SIRIUS BANK &bull; INTELLIGENCE DESK</div><h1>Your banking query, understood.</h1><p>A calm, private first line of support for everyday banking questions.</p><div class="trust">&#10022; Powered by fine-tuned DistilBERT &nbsp;&bull;&nbsp; 77 banking intents &nbsp;&bull;&nbsp; Test Macro-F1 91.06%</div></div>', unsafe_allow_html=True)

    with data_dashboard:
        st.markdown('<div class="section-kicker">SIRIUS intelligence overview</div>', unsafe_allow_html=True)
        st.header("The data behind the desk")
        st.write("A quick view of the BANKING77 world: 77 fine-grained banking intents, 13,083 customer queries, and a reserved official test set.")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Training queries", "9,002")
        c2.metric("Validation queries", "1,001")
        c3.metric("Official test", "3,080")
        c4.metric("Banking intents", "77")
        left, right = st.columns(2)
        with left:
            class_figure = root / "figures/class_distribution_all_intents.png"
            if class_figure.exists():
                st.image(str(class_figure), caption="Distribution across all BANKING77 intents.", width="stretch")
            diagnostic = root / "figures/class_balance_diagnostic.png"
            if diagnostic.exists():
                st.image(str(diagnostic), caption="Class-balance diagnostic used during EDA.", width="stretch")
        with right:
            length_figure = root / "figures/text_length_distribution.png"
            if length_figure.exists():
                st.image(str(length_figure), caption="Customer-query length distribution.", width="stretch")

    with atlas:
        st.markdown('<div class="section-kicker">Explore the banking language</div>', unsafe_allow_html=True)
        st.header("Intent atlas")
        st.write("Choose an intent to inspect real test queries, class-level performance, and common confusions.")
        selected_intent = st.selectbox(
            "Select a banking intent",
            list(enumerate(BANKING77_INTENTS)),
            format_func=lambda item: f"{item[0]} · {item[1]}",
        )
        intent_id, intent_name = selected_intent
        friendly_name = intent_name.replace("_", " ").replace("?", "").capitalize()
        category = intent_category(intent_name)
        st.markdown(f'<div class="atlas-card"><span class="mini-label">SIRIUS banking desk interpretation</span><br><strong>{friendly_name}</strong><br><b>Category:</b> {category}<br>This intent represents customer questions or support requests about <b>{friendly_name.lower()}</b>. Use the examples below to see how real customer language maps to this category.</div>', unsafe_allow_html=True)
        per_class_path = root / "results/per_class_metrics.csv"
        predictions_path = root / "results/predictions/test_predictions.csv"
        confusion_path = root / "results/top_confusions.csv"
        metric_row = None
        if per_class_path.exists():
            per_class = pd.read_csv(per_class_path)
            class_column = per_class.columns[0]
            metric_row = per_class[per_class[class_column].astype(str) == str(intent_id)]
        if metric_row is not None and not metric_row.empty:
            row = metric_row.iloc[0]
            a, b, c, d = st.columns(4)
            a.metric("Precision", f"{float(row['precision']):.1%}")
            b.metric("Recall", f"{float(row['recall']):.1%}")
            c.metric("F1", f"{float(row['f1-score']):.1%}")
            d.metric("Test examples", int(row['support']))
        if predictions_path.exists():
            predictions = pd.read_csv(predictions_path)
            examples = predictions[predictions["label"] == intent_id].copy()
            st.subheader("What customers actually say")
            if not examples.empty:
                display_columns = ["text"]
                if "E3_finetuned_distilbert" in examples.columns:
                    display_columns.append("E3_finetuned_distilbert")
                st.dataframe(examples[display_columns].head(8).rename(columns={"text": "Customer query", "E3_finetuned_distilbert": "Fine-tuned prediction ID"}), hide_index=True, width="stretch")
        if confusion_path.exists():
            confusions = pd.read_csv(confusion_path)
            related = confusions[(confusions["true_intent"] == intent_name) | (confusions["predicted_intent"] == intent_name)].head(8).copy()
            st.subheader("Where the model can hesitate")
            if related.empty:
                st.success("No top confusion pair is associated with this intent.")
            else:
                related["category"] = related["true_intent"].map(intent_category)
                related = related[["category", "true_intent", "predicted_intent", "count"]]
                st.dataframe(related.rename(columns={"category": "Banking category", "true_intent": "True intent", "predicted_intent": "Predicted intent", "count": "Confusions"}), hide_index=True, width="stretch")

    with model_lab:
        st.markdown('<div class="section-kicker">Evidence, not guesswork</div>', unsafe_allow_html=True)
        st.header("Model comparison")
        st.write("Macro-F1 is the primary metric because every banking intent receives equal weight.")
        if not metrics.empty:
            chart = metrics.set_index("experiment")["macro_f1"].rename("Macro-F1")
            st.bar_chart(chart, y="Macro-F1", color="#2563EB")
            st.dataframe(metrics[["experiment", "accuracy", "macro_f1", "weighted_f1"]].rename(columns={"experiment": "Experiment", "accuracy": "Accuracy", "macro_f1": "Macro-F1", "weighted_f1": "Weighted-F1"}).style.format({"Accuracy": "{:.2%}", "Macro-F1": "{:.2%}", "Weighted-F1": "{:.2%}"}), hide_index=True, width="stretch")
        if comparison_figure.exists():
            st.image(str(comparison_figure), caption="Measured Macro-F1 comparison from the executed experiments.", width="stretch")

        st.subheader("Training dynamics")
        history_files = {
            "TF-IDF + Logistic Regression": None,
            "BiLSTM": root / "results/logs/bilstm_history.json",
            "Frozen DistilBERT": root / "results/logs/04_distilbert_frozen_history.json",
            "Fine-tuned DistilBERT": root / "results/logs/05_distilbert_finetuning_history.json",
            "Fine-tuned DistilBERT, learning rate 5e-5": root / "results/logs/06_experiments_lr_5e-5_history.json",
        }
        selected_history = st.selectbox("Choose a training run", list(history_files))
        history_path = history_files[selected_history]
        if history_path is None:
            st.info("TF-IDF + Logistic Regression is a classical one-fit baseline, not an epoch-based neural training loop. Its measured final metrics are shown above, so loss curves are not available for this model.")
        elif history_path.exists():
            raw_history = json.loads(history_path.read_text())
            history = raw_history["history"] if isinstance(raw_history, dict) else raw_history
            history_frame = pd.DataFrame(history).set_index("epoch")
            loss_columns = [column for column in ("train_loss", "validation_loss") if column in history_frame]
            score_columns = [column for column in ("validation_accuracy", "validation_macro_f1") if column in history_frame]
            left_plot, right_plot = st.columns(2)
            with left_plot:
                st.caption("Loss across epochs")
                st.line_chart(history_frame[loss_columns], color=["#f1c66d", "#6dd3e3"])
            with right_plot:
                st.caption("Validation quality across epochs")
                st.line_chart(history_frame[score_columns], color=["#6dd3e3", "#f1c66d"])
            final_score = float(history_frame["validation_macro_f1"].iloc[-1])
            st.info(f"Interpretation: {selected_history} finishes at validation Macro-F1 {final_score:.3f}. A decreasing loss and rising validation score indicate learning; a widening validation loss would be a warning sign for overfitting.")

    with predict:
        st.markdown('<div class="chat-bubble"><span class="mini-label">SIRIUS assistant</span><br><b>Good morning, Saibou.</b><br>Tell me what happened with your banking request and I will route it to the most relevant support intent.</div>', unsafe_allow_html=True)
        st.markdown('<div class="section-kicker">Secure conversation</div>', unsafe_allow_html=True)
        st.subheader("Tell us what happened")
        st.caption("Choose a suggestion or write your own message below.")
        if "query_text" not in st.session_state:
            st.session_state["query_text"] = "Why was my cash withdrawal declined?"

        def use_suggestion(prompt: str) -> None:
            """Place a suggested customer message in the editable query box."""
            st.session_state["query_text"] = prompt

        quick = st.columns(3)
        quick_prompts = ["My card payment was declined", "I do not recognize a transfer", "How long will my transfer take?"]
        for index, (column, prompt) in enumerate(zip(quick, quick_prompts)):
            column.button(prompt, key=f"suggestion_{index}", on_click=use_suggestion, args=(prompt,), width="stretch")
        text = st.text_area("Write your own banking query", key="query_text", height=120, placeholder="Example: I was charged twice for the same purchase")
        if not checkpoint.exists():
            st.warning("Run the fine-tuning notebook first to create the checkpoint.")
        else:
            @st.cache_resource
            def load_model():
                return (
                    AutoTokenizer.from_pretrained(checkpoint),
                    AutoModelForSequenceClassification.from_pretrained(checkpoint),
                )

            if st.button("Predict intent", type="primary", width="stretch") and text.strip():
                tokenizer, model = load_model()
                encoded = tokenizer(text, return_tensors="pt", truncation=True, max_length=64)
                with torch.no_grad():
                    probabilities = torch.softmax(model(**encoded).logits, dim=1)[0]
                top_probabilities, top_indices = torch.topk(probabilities, k=3)
                predicted_id = int(top_indices[0].item())
                predicted_name = BANKING77_INTENTS[predicted_id]
                st.markdown(f'<div class="result-bubble"><span class="mini-label">SIRIUS routing decision</span><br><b>We would route this to:</b><br><span style="font-size:1.25rem;color:#0b6e73">{predicted_name}</span><br><span style="color:#52708e">Intent ID {predicted_id} • Confidence {float(top_probabilities[0].item()):.1%}</span></div>', unsafe_allow_html=True)
                rows = []
                for probability, index in zip(top_probabilities, top_indices):
                    intent_id = int(index.item())
                    rows.append({
                        "Rank": len(rows) + 1,
                        "Intent ID": intent_id,
                        "Intent name": BANKING77_INTENTS[intent_id],
                        "Confidence": float(probability.item()),
                    })
                st.dataframe(
                    pd.DataFrame(rows).style.format({"Confidence": "{:.2%}"}),
                    hide_index=True,
                    width="stretch",
                )
                st.caption("Intent names follow the official BANKING77 label order. This is a local model prediction, not a banking transaction decision.")
                st.session_state["last_prediction"] = {"intent": predicted_name, "confidence": float(top_probabilities[0].item())}


    with errors:
        st.subheader("Most frequent confusion pairs")
        confusion_path = root / "results/top_confusions.csv"
        if confusion_path.exists():
            confusion = pd.read_csv(confusion_path).head(10)
            confusion["pair"] = confusion["true_intent"] + " → " + confusion["predicted_intent"]
            st.bar_chart(confusion.set_index("pair")["count"], color="#F59E0B")
            st.dataframe(confusion[["true_intent", "predicted_intent", "count"]], hide_index=True, width="stretch")
        else:
            st.info("Run the final evaluation to create the confusion analysis file.")


if __name__ == "__main__":
    main()
